= Available data
:author: Herman Tatani
:revdate: October, 19 2022

== CMR catalog

====
CMR (Common Metadata Repository) is a tool that stores metadata of all NASA satellite data, which therefore brings together a wide variety of different fields.
The goal of the CMR is therefore to be able to access the data that interests us by sending a request on its metadata via the API.
====

There are many data catalog available on the MAAP platform accessible through the CMR API.

IMPORTANT: To have description of each dataset of each catalog, please visit the EDAV frontend by the following the link link:https://portal.val.esa-maap.org/portal-val/ESA/explore[EDAV frontend]

=== MAAP catalog

* *ESACCI_Biomass_L4_AGB*
* *AFRISAR_ONERA*
* *INDREX2*
* *AFRISAR_DLR*
* *TROPISAR*
* *BIOSAR3*
* *BIOSAR2*
* *BIOSAR1*

=== NASA catalog

* *ABoVE_UAVSAR_PALSAR*
* *AfriSAR:_Canopy_Structure_Derived_from_PolInSAR_and_Coherence_TomoSAR_NISAR_tools*
* *AfriSAR:_Rainforest_Canopy_Height_Derived_from_PolInSAR_and_Lidar_Data,_Gabon*
* *AfriSAR_AGB_Maps_1681*
* *AfriSAR_LVIS_L2_Geolocated_Surface_Elevation_Product_V001*
* *AfriSAR_UAVSAR_Coreg_SLC*
* *GEDI02_A*
* *GEDI02_B*

=== User data catalog

* *EVS_ASR_DEMO*
* *Agb_compute_linear_model*
* *Georef_Ecosse_classif*
* *ratio_VH_VV_Biosar1_105*

TIP: A user can also visualize on EDAV other data generated by ingest function.

=== ESA PDGS catalog

* *ALOS_PALSAR*

=== Creodias catalog

* *S2_MSIL2A*
* *Sentinel1_GRD_COG*

=== External data catalog

* *FOS plots*
* *Biosar 1*
* *Globbiomass*
* *Tomographic biomass Onera Lope*
* *GEDI Congo derived height*
* *GEDI L2A RH*
* *GEDI L4B*

== S3 data
